social_auth_linkedin.settings:
  type: config_object
  label: 'Social Auth Linkedin settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
    scopes:
      type: string
      label: 'Requested scopes to make API calls'
    api_calls:
      type: string
      label: 'API calls which will retrieve data'
